apiVersion: v1
kind: ConfigMap
metadata:
  name: radius-plugin-config
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: radius-plugin
    spec:
      version: v1.0
      init:
        command: [sh, -c]
        args:
          - |
            wget -O jq https://github.com/jqlang/jq/releases/download/jq-1.7.1/jq-linux64
            chmod +x ./jq
      generate:
        command: [sh, -c]
        args:
          - |
            echo "{\"kind\": \"ApplicationDeployment\", \"apiVersion\": \"radapp.io/v1alpha3\", \"metadata\": { \"name\": \"argodemo\", \"namespace\": \"default\"}, \"spec\": { \"template\": $(./jq -R -s '.' < app.bicep)}}"
      discover:
        fileName: "*.bicep"
