kind: ApplicationDeployment
apiVersion: radapp.io/v1alpha3
metadata:
  name: manualdemo
  namespace: default
spec:
  template: |
    // Import the set of Radius resources (Applications.*) into Bicep
    import radius as radius

    @description('The ID of your Radius Application. Set automatically by the rad CLI.')
    param application string

    resource demo 'Applications.Core/containers@2023-10-01-preview' = {
      name: 'demo'
      properties: {
        application: application
        container: {
          image: 'ghcr.io/radius-project/samples/demo:latest'
          ports: {
            web: {
              containerPort: 4000
            }
          }
        }
      }
    }
